# This file was generated by GoReleaser. DO NOT EDIT.
cask "clavik" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/clavik"]
    end
  end

  version "1.0.3"

  on_macos do
    on_arm do
      sha256 "41424861b3d2204cf9e11a69e1a6112a6eddddb63f56b36bc5c837d42d616bcf"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "77c1291d052004082d29635deb776aa29962f627c411a3764cd02a3878900b8c"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "94affe5e8f1d8f19bd1f4bc1758db90e2f7481df43d324cb28d0598ac1ca2d9f"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ffca957e9480c9ef3683bd7023559579122a70e294917de37c45912b53587b7f"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "clavik"
  desc "Command-line client for the Clavik vault"
  homepage "https://clavik.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clavik"

  # No zap stanza required
end
