# This file was generated by GoReleaser. DO NOT EDIT.
cask "clavik" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "83314518187989e48e22b8abeac30259ae1b11128455bf13a923b4b9656b6ee7"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a50b95f7e674b4bf3325b4a16af835d1592bf2cb68f1134dc899fb9b1c4e1f8"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bc5c1652c2296b1238a4c6ac45aecedf7c21bf638438b49b0680a48a4efddaa4"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "13bcd0a59c93be0e8f956d4bd974bb0ec9e26c40f8a2856fcc79557688d98e97"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "clavik"
  desc "Command-line client for the Clavik vault"
  homepage "https://clavik.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clavik"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clavik"]
    end
  end

  # No zap stanza required
end
