# This file was generated by GoReleaser. DO NOT EDIT.
cask "clavik" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "5dcd1eeef10c685c2ddf97bc9b319abaef9262d7a59b1ac6c5135a34e4454e5d"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf4f33c7f6362f3c027cc8a25c50e085247c98c718e82504ab3c116cdf388662"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7a7ed51a0fe670c44da4e8469283252b8e3fd3f814fbf0df236fa04c727395a4"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc1fb50c735d4af536ad77186c02edbf1341add63d59b09f53cf4929debdb38c"
      url "https://github.com/clavik-io/clavik-cli/releases/download/v#{version}/clavik_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "clavik"
  desc "Command-line client for the Clavik vault"
  homepage "https://clavik.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clavik"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clavik"]
    end
  end

  # No zap stanza required
end
